// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iyagntncuhajyktsqtmm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml5YWdudG5jdWhhanlrdHNxdG1tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2Nzc2ODUsImV4cCI6MjA2MDI1MzY4NX0.O3NpiAwanBvmcHfeq5EHlIOOzErPo1Gy3eXP-R5-cVA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});